"""added light requitement choices to plant table

Revision ID: 0fe714db26b0
Revises: bf4008dab81e
Create Date: 2023-06-08 10:02:26.591288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe714db26b0'
down_revision = 'bf4008dab81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('light_req',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('low', 'medium', 'high', name='light_requirement'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('light_req',
               existing_type=sa.Enum('low', 'medium', 'high', name='light_requirement'),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
