"""updated models, added join table

Revision ID: 804b604598b2
Revises: b561a3f1e4aa
Create Date: 2023-06-07 09:31:42.863691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b604598b2'
down_revision = 'b561a3f1e4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('light_req', sa.String(length=100), nullable=True),
    sa.Column('water_req', sa.String(length=100), nullable=True),
    sa.Column('fertilizer_req', sa.String(length=100), nullable=True),
    sa.Column('pests', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owned_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_owned_plants_owner_id_owners')),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_owned_plants_plant_id_plants')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owned_plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
