"""updated reqs

Revision ID: aed9fb7f8535
Revises: 0fe714db26b0
Create Date: 2023-06-09 11:59:43.983585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed9fb7f8535'
down_revision = '0fe714db26b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('water_req',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('low', 'medium', 'high', name='water_requirement'),
               nullable=False)
        batch_op.alter_column('fertilizer_req',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('low', 'medium', 'high', name='fertilizer_requirement'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('fertilizer_req',
               existing_type=sa.Enum('low', 'medium', 'high', name='fertilizer_requirement'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('water_req',
               existing_type=sa.Enum('low', 'medium', 'high', name='water_requirement'),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
